#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid2 voila
jupyter labextension enable @jupyter-widgets/jupyterlab-manager qgrid2 voila

jupyter nbextension enable --py --sys-prefix voila
jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension


