#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid2
jupyter labextension enable @jupyter-widgets/jupyterlab-manager qgrid2
jupyter labextension enable @jupyter-voila/jupyterlab-preview

jupyter nbextension enable --py --sys-prefix voila
jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension


